model_params:
  h_dim: 256
  x_dim: 2048

train_params:
  strategy: full  # full or mini
  epoch: 22
  batch_size: 1
  lr: 0.0001
  resume: False
  ckpt_file: None
  tl: False
  
  early_stop: 10
  learning_rate_patience: 2
  no_workers: 4

test_params:
  strategy: full  # full or mini
  batch_size: 1
  no_workers: 8