# Model categories in model.py
model_class: DAM_v3

# BDDADataset_seg is a processed BDDA dataset that includes semantic segmentation images.
dataset: BDDADataset_seg

last_weights: None

best_weights: None

model_params:
  img_size: [224,224]
  use_map: True
  use_DBB: True

  transformer_params:
    add_and_norm: True
    fuse_idx: [0, 1]
    num_att_heads: [4, 2, 2, 2]

  pretrained_backbone: True
  train_backbone: True
  num_encoder_layers: 4 # 1-4 
  clip_size: 16

train_params:
  no_epochs: 20
  lr: 0.0001
  loss:
    kldiv: True
    kldiv_coeff: 1.0
    cc: True
    cc_coeff: -0.5
    nss: False
    nss_coeff: 1.0
    sim: True
    sim_coeff: -0.5
    l1: False
    l1_coeff: 1.0
  lr_sched: True
  early_stop: True
  optimizer: Adam
  batch_size: 4
  log_interval: 10
  no_workers: 8 # number of workers for dataloader
  weighted_sampler: False # select "hard" samples more frequently during training, may not use all samples
  weighted_loss: False # assigns higher weights to "hard" samples in loss calculation
  weight_type: KLdiv

test_params:
  batch_size: 4
  eval: quick # Options: full, quick (10% of the data), null (do not evaluate)
  metrics: [KLdiv, NSS, SIM, CC] 
  save_images: True # save saliency maps