model_class: VidNeXt

model_params:
  img_size: [224, 224]
  segment_length: 5
  segment_overlap: 1

train_params:
  strategy: full
  no_epochs: 50
  batch_size: 1
  early_stop: 10
  lr: 0.000002
  learning_rate_patience: 2
  no_workers: 4

test_params:
  strategy: full
  batch_size: 2
  no_workers: 8